e-class-35t:
  script:
    - source /tools/setup.sh
    - source /tools/hw_tools/viv2018.sh
    - cd fpga/boards/artya7-35t/e-class
    - make call_manager set_jtag_bscan2e generate_verilog generate_boot_files ip_build arty_build generate_mcs
    - make restore
    - ./manager.sh nuke
  only:
    refs:
      - master
  tags:
    - shakti-runner

e-class-100t:
  script:
    - source /tools/setup.sh
    - source /tools/hw_tools/viv2018.sh
    - cd fpga/boards/artya7-100t/e-class
    - make call_manager set_jtag_bscan2e generate_verilog ip_build arty_build generate_mcs
    - make restore
    - ./manager.sh nuke
  only:
    refs:
      - master
  tags:
    - shakti-runner

c-class-100t:
  script:
    - source /tools/setup.sh
    - source /tools/hw_tools/viv2018.sh
    - cd fpga/boards/artya7-100t/c-class
    - make call_manager set_jtag_bscan2e generate_verilog ip_build arty_build generate_mcs
    - make restore
    - ./manager.sh nuke
  only:
    refs:
      - master
  tags:
    - shakti-runner
