
e-class-35t:
  script:
    - source /tools/setup.sh
    - source /tools/viv208.sh
    - cd fpga/boards/artya7-35t/e-class
    - make call_manager set_jtag_bscan2e generate_verilog ip_build arty_build generate_mcs
    - cp fpga_project/e-class/fpga_top.mcs ../../../../
  only:
    refs:
      - master
    changes:
      - fpga/boards/artya7-35t/e-class/*
  artifacts:
    name: e-class-35t
    paths:
      - fpga_top.mcs
  tags:
    - core-runner
    - shakti-runner
